config/routes.rb
Rails.application.routes.draw do

  root "films#index"
  resources :films do
    member do
      post :create_film_checkout
      patch :return_film
    end
  end

end

app/models/film.rb
class Film < ActiveRecord::Base
  has_many :users, through: :film_checkouts
  has_many :film_checkouts
  scope :by_rating, -> { order('rating DESC')}

end

app/models/film_checkout.rb
class FilmCheckout < ActiveRecord::Base
  belongs_to :film
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :films, through: :film_checkouts
  has_many :film_checkouts

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController

  before_action :find_film, only: [:show, :create_film_checkout, :return_film]

  def index
    if params[:order].blank?
      @films = Film.by_rating
    else
      order = params[:order]
      @films = Film.order("#{order} DESC")
    end
  end

  def show
    @film_checkout = FilmCheckout.new
    @checkout_history = @film.film_checkouts
  end

  def create_film_checkout
    ActiveRecord::Base.transaction do
      checkout_time = DateTime.now

      FilmCheckout.create(film_id: @film.id,
                          user_id: params[:film_checkout][:user_id],
                          checkout_time: checkout_time,
                          return_time: nil)

      @film.update_attribute(:available, false)
    end
    redirect_to root_path
  end

  def return_film
    ActiveRecord::Base.transaction do
      return_time = DateTime.now
      film_return = @film.film_checkouts.where(return_time: nil).last

      film_return.update_attribute(:return_time, return_time)
      @film.update_attribute(:available, true)
    end
    redirect_to root_path
  end

  protected

  def find_film
    @film = Film.find(params[:id])
  end

  def film_params
    params.require(:film).permit(:title, :rating, :genre, :available)
  end

  def film_checkout_params
    params.require(:film_checkout).permit(:user_id, :film_id, :checkout_time, :return_time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/films/_checkout_form.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <%= simple_form_for film_checkout, url: create_film_checkout_film_path do |f| %>
      <div class='form-group'>
        <%= f.label :user_id, 'Select Renter'%>
      </div>
      <div class='form-group'>
        <%= f.input :user_id, label: false, include_blank: false, collection: User.all.collect{|u| [u.full_name, u.id]}%>
      </div>
      <div class='form-group'>
        <%= f.submit "Checkout Film", class: "btn btn-primary btn-sm"%>
      </div>
    <%end%>
  </div>
</div>

app/views/films/_checkout_history_table.html.erb
<h3> Checkout History </h3>
<table class="table table-striped table-bordered table-condensed table-hover">
  <thead>
    <th>Renter</th>
    <th>Checkout Date</th>
    <th>Return Date</th>
  </thead>

  <tbody>
  <%checkout_history.each do |ch|%>
    <tr>
      <td><%= ch.user.full_name%></td>
      <td><%= ch.checkout_time.strftime('%b %e, %l:%M %p')%></td>
      <td><%= ch.return_time.nil? ? 'Pending' : ch.return_time.strftime('%b %e, %l:%M %p')%></td>
    </tr>
  <%end%>
  </tbody>
</table>

app/views/films/_film_table.html.erb
<table class="table table-striped table-bordered table-condensed table-hover">
    <thead>
      <th>Title</th>
      <th>Genre</th>
      <th>Rating</th>
      <th>Available?</th>
    </thead>

    <tbody>
    <%films.each do |f|%>
      <tr>
        <td><%= link_to f.title, film_path(f.id)%></td>
        <td><%= f.genre%></td>
        <td><%= f.rating%></td>
        <td><%= f.available? ? 'Yes': 'No'%></td>
      </tr>
    <%end%>
    </tbody>
  </table>

app/views/films/_return_form.html.erb
<div class='row margin-top'>
  <div class='col-xs-12'>
    <%= simple_form_for film_checkout, url: return_film_film_path, method: :patch do |f| %>
      <div class='form-group'>
        <%= f.submit "Return Film", class: "btn btn-primary btn-sm"%>
      </div>
    <%end%>
  </div>
</div>

app/views/films/index.html.erb
<div id='film-table'>

  <h1 id="movie-header" class="text-center"> Welcome to the Society of Grownups Movie Kiosk!</h1>

  <div id="movie-table">
    <%= render 'film_table', films: @films%>
  </div>

  <h3 class="text-center">View Movies by:</h3>
  <div class="text-center">
    <span><%= link_to 'Title', root_path(order: 'title'), remote: true, class: "btn btn-primary"%></span>
    <span><%= link_to 'Genre', root_path(order: 'genre'), remote: true, class: "btn btn-success"%></span>
    <span><%= link_to 'Rating', root_path(order: 'rating'), remote: true, class: "btn btn-danger"%></span>
    <span><%= link_to 'Availability', root_path(order: 'available'), remote: true, class: "btn btn-info"%></span>
  </div>
</div>

app/views/films/index.js.erb
$("#movie-table").html("<%= j render("films/film_table", films: @films)%>");

app/views/films/show.html.erb
<div class='container'>
  <div class='col-xs-4'>
    <div class='margin-top'><%= image_tag @film.image_path%></div>
    <div class='margin-top'><%= link_to 'Go Back', root_path, class: 'btn btn-danger'%></div>
  </div>
  <div class='col-xs-8'>
    <h1><%= @film.title%></h1>
    <h4 class='margin-top'>Description:</h3>
    <p><%=@film.description%></p>
    <h4 class='margin-top'>This Film is Currently:
      <% if @film.available?%>
      <span class="btn btn-success" id="available">Available For Rent</span>
      <div class='margin-top' id="checkout-form">
        <%= render 'checkout_form', film_checkout: @film_checkout %>
      </div>
      <%else%>
      <span class="btn btn-danger" id="checked-out">Checked Out</span>
        <%= render 'return_form', film_checkout: @film_checkout%>
      <%end%>
    </h4>
    <div class='margin-top'>
      <%unless @checkout_history.blank?%>
        <%= render 'checkout_history_table', checkout_history: @checkout_history%>
      <%end%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SogMovieKiosk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>